# Generated by Django 3.1.14 on 2022-10-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20221026_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='previous_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pokemon_entities.pokemon'),
        ),
    ]
