# Generated by Django 3.1.14 on 2022-10-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20221029_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, default='описание отсутствует', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='previous_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_forms', to='pokemon_entities.pokemon', verbose_name='Предыдущая ступень эволюции'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_en',
            field=models.CharField(blank=True, default='неизвестно', max_length=200, verbose_name='Название на английском языке'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_jp',
            field=models.CharField(blank=True, default='неизвестно', max_length=200, verbose_name='Название на японском языке'),
        ),
    ]
